services:

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: employees_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  spark:
    image: jupyter/pyspark-notebook
    container_name: spark_app
    ports:
      - "8888:8888"
    restart: always

volumes:
  postgres_data: